# Generated by Django 3.0.4 on 2020-04-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='Vasanth', max_length=30)),
                ('Student_Id', models.CharField(default='Y13EC3265', max_length=50)),
                ('Batch', models.CharField(default='2016-20', max_length=50)),
                ('Bookname', models.CharField(default='Fundamentals of Electric Circuits (Edition 5)', max_length=50)),
                ('Author', models.CharField(default='Charles K. Alexander, Matthew N. O. Sadiku', max_length=50)),
                ('ReserveDate', models.CharField(default='20/03/2020', max_length=50)),
                ('RenewDate', models.CharField(default='NaN', max_length=50)),
            ],
        ),
    ]
